### ISSUE TITLE
Escape from Umbrafen

### ISSUE THREAD

**Issue by billskie** [BillytheOrc/ProjectTempest-ISSUETRACKER#22] opened 2018-07-19 22:15 UTC
Quest in Umbrafen Village (83, 80 or so) - Escorting Kayra Longmane:

Second set of adds that spawn (Umbrafen Slavebinders) stand there and don't auto-engage the player / Kayra. She then (not flagged for combat) leaves towards the refuge.

Fix: Make the Slavebinders run at the player or Kayra immediately after spawn.

**Comment by BillytheOrc** [comment] 2018-07-20 00:01
The easiest fix for this seems to be EventAI attack on spawn. Wish AnonXS was part of this to ask for advice :D

**Comment by AnonXS** [comment] 2018-07-20 10:02
As escorts are core scripted, this attack spawner on spawn should be handled in the escort script.

**Comment by BillytheOrc** [comment] 2018-07-20 10:56
@AnonXS Yeah, you're right.

**Comment by BillytheOrc** [comment] 2018-07-20 15:36
I can't seem to reproduce this issue. The moment she starts running they get into combat with her.

**Closed** 2018-07-20 15:36 UTC
